spring:
  application:
    name: patient

  datasource:
    url: jdbc:postgresql://localhost:5432/patientdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  logging:
    level:
      org.hibernate.orm.jdbc.bind: trace
      org.flywaydb: DEBUG
      org.springframework.boot.autoconfigure.flyway: DEBUG

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: patient-created-audit
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  app:
    outbox:
      poll-interval-ms: 5000
