apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service-config
  namespace: patient
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patientdb
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
