apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: patient-service-pdb
  namespace: patient
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: patient-service
